cass_web_admin/dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'
urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^cluster/(?P<cluster>[0-9]*)$', views.clusterDetail, name='cluster'),
  url(r'^node/(?P<node>[0-9]*)$', views.nodeDetail, name='node'),
  url(r'^poll/(?P<cluster>[0-9]*)$', views.pollGraphData, name='pollGraph'),
]

cass_web_admin/urls.py
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

urlpatterns = [
    url(r'^', include('cass_web_admin.dashboard.urls')),
    url(r'^admin/', admin.site.urls),
]

cass_web_admin/dashboard/models.py
from __future__ import unicode_literals

from django.db import models
import json

# Create your models here.
class MBean(models.Model):
  mbean = models.CharField(max_length=512)
  attribute = models.CharField(max_length=128)
  path = models.CharField(max_length=128, blank=True)
  type = models.CharField(max_length=16)
  status = models.BooleanField(default=True)

  @classmethod
  def create(cls, mbean, attribute, path, type):
    mbean = cls(mbean=mbean,attribute=attribute,path=path,type=type)
    return mbean

  def __str__(self):
    return json.dumps(self.getJson())
    
  def getJson(self):
    data = {"type":self.type, 
      "mbean":self.mbean, 
      "attribute":self.attribute, 
      "path":self.path}
    return data

class NetworkBlock(models.Model):

  BLOCK_TYPES = (
   (1, 'Cluster'),
   (2, 'Datacenter'),
   (3, 'Rack'),
   (4, 'Node')
  )
  block_name = models.CharField(max_length=128)
  block_type = models.IntegerField(default=0, choices=BLOCK_TYPES)
  
  BLOCK_CLUSTER = 1
  BLOCK_DATACENTER = 2
  BLOCK_RACK = 3
  BLOCK_NODE = 4

  def __str__(self):
    index = self.block_type -1
    resultTuple = NetworkBlock.BLOCK_TYPES[index]
    result = resultTuple[1]
    return "%s(%s)" % (self.block_name,result)

class Cluster(NetworkBlock):
  cluster_type = models.TextField(max_length=32)
  cluster_version = models.TextField(max_length=16)

  def getDatacenters(self):
    datacenters = Datacenter.objects.filter(parent=self)
    return datacenters

class Datacenter(NetworkBlock):
  parent = models.ForeignKey(Cluster, on_delete=models.CASCADE, related_name="%(class)s_")

  def getRacks(self):
    racks = Rack.objects.filter(parent=self)
    return racks

class Rack(NetworkBlock):
  parent = models.ForeignKey(Datacenter, on_delete=models.CASCADE, related_name="%(class)s_")

  def getNodes(self):
    nodes = Node.objects.filter(parent=self)
    return nodes

  def getRacks(self):
    racks = Rack.objects.filter(parent=self)
    return racks

class Node(NetworkBlock):
  parent = models.ForeignKey(Rack, on_delete=models.CASCADE, related_name="%(class)s_")
  mbeans = models.ManyToManyField(MBean)

cass_web_admin/dashboard/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse, Http404

import requests
import json

from .models import MBean, Cluster, Node

# Create your views here.
def index(request):
  clusters = Cluster.objects.all()
  return render(request, 'index.html', {"clusters":clusters})

def clusterDetail(request, cluster):
  clusterData = Cluster.objects.get(pk=cluster)
  return render(request, "cluster.html", {"cluster":clusterData})

def nodeDetail(request, node):
  nodeData = Node.objects.get(pk=node)
  return render(request, 'node.html', {"node": nodeData})

def pollGraphData(request, cluster):
  nodes = Node.objects.filter(parent=cluster)
  jmxConns = []
  for node in nodes:
    jmxConns.append(node.node_jmx_url+"/")
  beans = MBean.objects.all()
  beansData = []
  for bean in beans:
    if bean.status == True:
      beansData.append(bean.getJson())

  responses = []
  for jmxConn in jmxConns:
    req = requests.post(jmxConn, data=json.dumps(beansData))
    responses.append(json.loads(req.content))

  results = []
  for resp in responses:
    count = 0
    for i in range(len(beans)):
      if beans[i].status == True:
	results.append(resp[count])
	count = count + 1

  return HttpResponse(json.dumps(results), content_type='application/json')

def execCommand(request):
  return HttpResponse(status=200)

cass_web_admin/dashboard/templates/base.html
<html>
  <head>
    {% block head %}
      {% block meta %}
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Meta, title, CSS, favicons, etc. -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
      {% endblock %}
      {% block title %}
      {% endblock %}
      {% block css %}
	{% load staticfiles %}
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="{% static 'fonts/css/font-awesome.min.css' %}" rel="stylesheet">
        <link href="{% static 'css/animate.min.css' %}" rel="stylesheet">
        <!-- Custom styling plus plugins -->
        <link href="{% static 'css/custom.css' %}" rel="stylesheet">
        <link href="{% static 'css/maps/jquery-jvectormap-2.0.3.css' %}" rel="stylesheet" />
        <link href="{% static 'css/icheck/flat/green.css' %}"rel="stylesheet" />
        <link href="{% static 'css/floatexamples.css' %}" rel="stylesheet" />
      {% endblock %}
    {% endblock %}
  </head>
  <body class="nav-md pace-done" style="height: 97%;">
  {% block body %}

        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">

                        <div class="navbar nav_title" style="border: 0;">
                            <a href="/" class="site_title"><i class="fa fa-paw"></i> <span>Cassandra</span></a>
                        </div>
                        <div class="clearfix"></div>

                        <!-- menu profile quick info -->
                        <div class="profile">
                            <div class="profile_pic">
                                <img src="{% static 'images/img.jpg' %}" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Welcome,</span>
                                <h2>Abdullah</h2>
                            </div>
                        </div>
                        <!-- /menu prile quick info -->
                        <div class="clearfix"></div>
                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">

                            <div class="menu_section">
                                <h3>Navigation Menu</h3>
                                <ul class="nav side-menu">
                                    <li><a><i class="fa fa-home"></i> View <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="display: none">
                                            <li><a href="cluster_view.html">Cluster View</a>
                                            </li>
                                            <li><a href="dc_view.html">DC View</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li><a><i class="fa fa-edit"></i>Operation<span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu" style="display: none">
                                            <li><a href="nodetool_op.html">Nodetool Operation</a>
                                            </li>
                                            <li><a href="cqlsh_op.html">CQLSH Operation</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Logout">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->

                    </div>
                </div>
                <!-- top navigation -->
                <div class="top_nav">

                    <div class="nav_menu">
                        <nav class="" role="navigation">
                            <div class="nav toggle" style="cursor: grab">
                                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                            </div>
                        </nav>
                    </div>

                </div>
                <!-- /top navigation -->


                <!-- page content -->
                <div class="right_col" role="main" style="min-height: 300px">
		{% block content %}
		{% endblock %}
                <br/>
                <!-- footer content -->
                    <footer>
                        <div class="copyright-info">
                            <p class="pull-right">Editor: Abdullah, 2016		
                            </p>
                        </div>
                        <div class="clearfix"></div>
                    </footer>
                    <!-- /footer content -->
                </div>
                <!-- /page content -->
                <div class="clearfix"></div>
            </div>
        </div>
  
          <div id="custom_notifications" class="custom-notifications dsp_none">
            <ul class="list-unstyled notifications clearfix" data-tabbed_notifications="notif-group">
            </ul>
            <div class="clearfix"></div>
            <div id="notif-group" class="tabbed_notifications">
            </div>
        </div>


      {% block js %}
	{% load staticfiles %}
	<script src="{% static 'js/lib/d3.min.js' %}"></script>
	<script src="{% static 'js/lib/jquery.min.js' %}"></script>
        <script src="{% static 'js/nprogress.js' %}"></script>


        <!--[if lt IE 9]>
        <script src="{% static '../assets/js/ie8-responsive-file-warning.js' %}"></script>
        <![endif]-->
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- gauge js -->
        <script src="{% static 'js/gauge/gauge.min.js' %}"></script>
        <script src="{% static 'js/gauge/gauge_demo.js' %}"></script>
        <!-- chart js -->
        <script src="{% static 'js/chartjs/chart.min.js' %}"></script>
        <!-- bootstrap progress js -->
        <script src="{% static 'js/progressbar/bootstrap-progressbar.min.js' %}"></script>
        <script src="{% static 'js/nicescroll/jquery.nicescroll.min.js' %}"></script>
        <!-- icheck -->
        <script src="{% static 'js/icheck/icheck.min.js' %}"></script>
        <!-- daterangepicker -->
        <script src="{% static 'js/moment/moment.min.js' %}"></script>
        <script src="{% static 'js/datepicker/daterangepicker.js' %}"></script>

        <script src="{% static 'js/custom.js' %}"></script>

        <!-- flot js -->
        <!--[if lte IE 8]><script type="text/javascript" src="js/excanvas.min.js"></script><![endif]-->
        <script src="{% static 'js/flot/jquery.flot.js' %}"></script>
        <script src="{% static 'js/flot/jquery.flot.pie.js' %}"></script>
        <script src="{% static 'js/flot/jquery.flot.orderBars.js' %}"></script>
        <script src="{% static 'js/flot/jquery.flot.time.min.js' %}"></script>
        <script src="{% static 'js/flot/date.js' %}"></script>
        <script src="{% static 'js/flot/jquery.flot.spline.js' %}"></script>
        <script src="{% static 'js/flot/jquery.flot.stack.js' %}"></script>
        <script src="{% static 'js/flot/curvedLines.js' %}"></script>
        <script src="{% static 'js/flot/jquery.flot.resize.js' %}"></script>
	{% endblock %}
      {% endblock %}
  </body>
</html>

cass_web_admin/dashboard/templates/cluster.html
{%extends 'base.html'%}
{%block title%}
  <title>{{cluster.block_name}}</title>
{%endblock%}
{%block content%}
  <h3>Cluster Topology</h3>
  <h6>{{cluster.block_name}}</h6>
  {%if cluster.getDatacenters|length > 0 %}
    <ul>
    {%for datacenter in cluster.getDatacenters %}
	<li>{{datacenter.block_name}}<br/><ul>
	{%for rack in datacenter.getRacks %}
		<li>{{rack.block_name}}<br/><ul>
		{%for nodes in rack.getNodes %}
		<li>{{nodes.block_name}}</li>
		{%endfor%}
		</ul></li>
	{%endfor%}
	</ul></li>
    {%endfor%}
    </ul>
  {%else%}
    <h3>No Nodes Added</h3>
  {%endif%}
  <h6>Add a new Node!</h6>
  <input type="text" value=""/>
  <input type="button" value="Add Node" />
{%endblock%}

cass_web_admin/dashboard/templates/index.html
{% extends 'base.html' %}
{% block title %}
<title>Index</title>
{%endblock%}
{%block content%}
<div class="row">
<br />
  {%if clusters%}
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="col-md-6">
      <h3>Cluster List</h3>
      <ul>
      {%for cluster in clusters%}
	<li><a href="{%url 'dashboard:cluster' cluster.id%}">{{cluster.block_name}}</a></li>

      {%endfor%}
      </ul>
    </div>
  </div>
  {%else%}
    <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="col-md-6">
      <h3>Empty <small>no content</small></h3>
    </div>
    <div class="col-md-6"></div>
  </div>
  <div class="col-md-12 col-sm-12 col-xs-12">...</div>
  <div class="clearfix"></div>
  {%endif%}
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="col-md-6">
      <h3>Add <small>new cluster</small></h3>
    </div>
    <div class="col-md-6"></div>
  </div>
  <div class="col-md-12 col-sm-12 col-xs-12">
  <input type="text" value=""/>
  <input type="button" value="Add Cluster"/>
 </div>
  <div class="clearfix"></div>
</div>
{%endblock%}

cass_web_admin/dashboard/templates/node.html
{%extends 'base.html'%}
{%block title%}
  {%if node%}
  <title>{{node.node_name}}</title>
  {%else%}
  <title>Unknown Node</title>
  {%endif%}
{%endblock%}
{%block content%}
  <div>Some Data</div>
{%endblock%}